// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ztbrbpvgqsefsvwjfkqb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0YnJicHZncXNlZnN2d2pma3FiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyMzk4NDEsImV4cCI6MjA2MzgxNTg0MX0.X5BT1eGAYXmYFcN0esxuqPz7wLEhhjYWX9BtMYNM7Cc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);